version: '3.7'
services:
  heritage-web:
    image: nginx:alpine
    container_name: heritage-web
    ports:
    - 3001:80
    volumes:
    - ./my_cross_app/build/web:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    depends_on:
    - heritage-api
  heritage-api:
    build: ./server
    container_name: heritage-api
    ports:
    - 8080:8080
    volumes:
    - ./server:/app
    restart: unless-stopped
    environment:
    - PYTHONPATH=/app
    command:
    - python3
    - -m
    - uvicorn
    - main:app
    - --host
    - 0.0.0.0
    - --port
    - '8080'
  firebase-cors-setup:
    image: google/cloud-sdk:alpine
    container_name: firebase-cors-setup
    volumes:
    - ./firebase_storage_cors.json:/firebase_storage_cors.json:ro
    - ./setup_firebase_cors.sh:/setup_firebase_cors.sh:ro
    command:
    - sh
    - -c
    - "echo 'Firebase CORS \uC124\uC815\uC740 \uC218\uB3D9\uC73C\uB85C \uC2E4\uD589\
      \uD558\uC138\uC694: ./setup_firebase_cors.sh'"
